"""create tables

Revision ID: 5c8ff6011aad
Revises: 
Create Date: 2024-02-01 18:24:16.917221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8ff6011aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_content_hash', sa.String(), nullable=True),
    sa.Column('outgoing_user_id', sa.Integer(), nullable=True),
    sa.Column('receiving_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outgoing_user_id'], ['users.id'], name=op.f('fk_messages_outgoing_user_id_users')),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name=op.f('fk_messages_receiving_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
