"""Starting seed file

Revision ID: d7337ce809e2
Revises: 5c8ff6011aad
Create Date: 2024-02-01 19:22:15.622708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7337ce809e2'
down_revision = '5c8ff6011aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))
        batch_op.alter_column('outgoing_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiving_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('_content_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_content_hash', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('receiving_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('outgoing_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###
